#!/bin/sh
. "$(dirname "$0")/_/husky.sh"


echo "\n>> Pre-push Hook: Checking branch name"

BRANCH=`git rev-parse --abbrev-ref HEAD`
PROTECTED_BRANCHES="^(master)"

if [[ "$BRANCH" =~ $PROTECTED_BRANCHES ]]
then
  echo "\n🚫  Cannot push to remote $BRANCH branch, please create your own branch and make a PR instead."
  echo "\nPlease use the command below if you still want to push to $BRANCH branch.\n\n\tgit push --no-verify\n" && exit 1
fi

echo ">> Finish checking branch name\n"

exit 0